version: '3'

services:

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  mongoexpress:
   image: mongo-express
   depends_on:
   - mongodb
   links:
     - mongodb
   ports:
       - 8081:8081
   environment:
     - ME_CONFIG_MONGODB_SERVER=mongodb